2013/12/26 07:11:50 [error] [exception.CException] exception 'CException' with message 'CAssetManager.basePath "/opt/lampp/htdocs/so/assets" is invalid. Please make sure the directory exists and is writable by the Web server process.' in /opt/lampp/htdocs/so/yii/framework/web/CAssetManager.php:138
Stack trace:
#0 /opt/lampp/htdocs/so/yii/framework/web/CAssetManager.php(123): CAssetManager->setBasePath('/opt/lampp/htdo...')
#1 /opt/lampp/htdocs/so/yii/framework/web/CAssetManager.php(217): CAssetManager->getBasePath()
#2 /opt/lampp/htdocs/so/yii/framework/web/CClientScript.php(510): CAssetManager->publish('/opt/lampp/htdo...')
#3 /opt/lampp/htdocs/so/yii/framework/web/CClientScript.php(547): CClientScript->getCoreScriptUrl()
#4 /opt/lampp/htdocs/so/yii/framework/web/CClientScript.php(348): CClientScript->getPackageBaseUrl('jquery')
#5 /opt/lampp/htdocs/so/yii/framework/web/CClientScript.php(208): CClientScript->renderCoreScripts()
#6 /opt/lampp/htdocs/so/yii/framework/web/CController.php(351): CClientScript->render('<!DOCTYPE html ...')
#7 /opt/lampp/htdocs/so/yii/framework/web/CController.php(788): CController->processOutput('<!DOCTYPE html ...')
#8 /opt/lampp/htdocs/so/protected/controllers/SiteController.php(72): CController->render('contact', Array)
#9 /opt/lampp/htdocs/so/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionContact()
#10 /opt/lampp/htdocs/so/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#11 /opt/lampp/htdocs/so/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#12 /opt/lampp/htdocs/so/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 /opt/lampp/htdocs/so/yii/framework/web/CWebApplication.php(282): CController->run('contact')
#14 /opt/lampp/htdocs/so/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/contact')
#15 /opt/lampp/htdocs/so/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#16 /opt/lampp/htdocs/so/index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/so/index.php?r=site/contact
HTTP_REFERER=http://localhost/so/index.php?r=site/page&view=about
---
2013/12/26 08:19:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gi".' in /opt/lampp/htdocs/so/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /opt/lampp/htdocs/so/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gi')
#1 /opt/lampp/htdocs/so/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /opt/lampp/htdocs/so/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/so/index.php?r=gi
---
2013/12/26 08:22:56 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /opt/lampp/htdocs/so/yii/framework/web/auth/CAccessControlFilter.php:182
Stack trace:
#0 /opt/lampp/htdocs/so/yii/framework/web/auth/CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 /opt/lampp/htdocs/so/yii/framework/web/filters/CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /opt/lampp/htdocs/so/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 /opt/lampp/htdocs/so/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 /opt/lampp/htdocs/so/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 /opt/lampp/htdocs/so/yii/framework/web/CController.php(291): CFilterChain->run()
#6 /opt/lampp/htdocs/so/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /opt/lampp/htdocs/so/yii/framework/web/CWebApplication.php(282): CController->run('admin')
#8 /opt/lampp/htdocs/so/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('user/admin')
#9 /opt/lampp/htdocs/so/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /opt/lampp/htdocs/so/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/so/index.php?r=user/admin
HTTP_REFERER=http://localhost/so/index.php?r=user/index
---
2013/12/26 08:23:04 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /opt/lampp/htdocs/so/yii/framework/web/auth/CAccessControlFilter.php:182
Stack trace:
#0 /opt/lampp/htdocs/so/yii/framework/web/auth/CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 /opt/lampp/htdocs/so/yii/framework/web/filters/CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /opt/lampp/htdocs/so/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 /opt/lampp/htdocs/so/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 /opt/lampp/htdocs/so/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 /opt/lampp/htdocs/so/yii/framework/web/CController.php(291): CFilterChain->run()
#6 /opt/lampp/htdocs/so/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /opt/lampp/htdocs/so/yii/framework/web/CWebApplication.php(282): CController->run('delete')
#8 /opt/lampp/htdocs/so/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('user/delete')
#9 /opt/lampp/htdocs/so/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /opt/lampp/htdocs/so/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/so/index.php?r=user/delete&id=4
HTTP_REFERER=http://localhost/so/index.php?r=user/view&id=4
---
2013/12/26 08:33:06 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /opt/lampp/htdocs/so/yii/framework/web/auth/CAccessControlFilter.php:182
Stack trace:
#0 /opt/lampp/htdocs/so/yii/framework/web/auth/CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 /opt/lampp/htdocs/so/yii/framework/web/filters/CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /opt/lampp/htdocs/so/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 /opt/lampp/htdocs/so/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 /opt/lampp/htdocs/so/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 /opt/lampp/htdocs/so/yii/framework/web/CController.php(291): CFilterChain->run()
#6 /opt/lampp/htdocs/so/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /opt/lampp/htdocs/so/yii/framework/web/CWebApplication.php(282): CController->run('delete')
#8 /opt/lampp/htdocs/so/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('user/delete')
#9 /opt/lampp/htdocs/so/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /opt/lampp/htdocs/so/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/so/index.php?r=user/delete&id=1
HTTP_REFERER=http://localhost/so/index.php?r=user/view&id=1
---
2013/12/26 09:29:57 [error] [exception.CException] exception 'CException' with message 'User and its behaviors do not have a method or closure named "validatePassword".' in /opt/lampp/htdocs/so/yii/framework/base/CComponent.php:266
Stack trace:
#0 /opt/lampp/htdocs/so/yii/framework/db/ar/CActiveRecord.php(227): CComponent->__call('validatePasswor...', Array)
#1 /opt/lampp/htdocs/so/protected/components/UserIdentity.php(26): CActiveRecord->__call('validatePasswor...', Array)
#2 /opt/lampp/htdocs/so/protected/components/UserIdentity.php(26): User->validatePassword('admin')
#3 /opt/lampp/htdocs/so/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#4 /opt/lampp/htdocs/so/yii/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#5 /opt/lampp/htdocs/so/yii/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#6 /opt/lampp/htdocs/so/yii/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#7 /opt/lampp/htdocs/so/protected/controllers/SiteController.php(94): CModel->validate()
#8 /opt/lampp/htdocs/so/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#9 /opt/lampp/htdocs/so/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /opt/lampp/htdocs/so/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /opt/lampp/htdocs/so/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /opt/lampp/htdocs/so/yii/framework/web/CWebApplication.php(282): CController->run('login')
#13 /opt/lampp/htdocs/so/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#14 /opt/lampp/htdocs/so/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /opt/lampp/htdocs/so/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/so/index.php?r=site/login
HTTP_REFERER=http://localhost/so/index.php?r=site/login
---
2013/12/26 09:31:08 [error] [php] Invalid argument supplied for foreach() (/opt/lampp/htdocs/so/yii/framework/web/auth/CPhpAuthManager.php:420)
Stack trace:
#0 /opt/lampp/htdocs/so/yii/framework/base/CModule.php(103): CWebApplication->getComponent()
#1 /opt/lampp/htdocs/so/protected/components/UserIdentity.php(32): CWebApplication->__get()
#2 /opt/lampp/htdocs/so/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#3 /opt/lampp/htdocs/so/yii/framework/validators/CInlineValidator.php(42): LoginForm->authenticate()
#4 /opt/lampp/htdocs/so/yii/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute()
#5 /opt/lampp/htdocs/so/yii/framework/base/CModel.php(159): CInlineValidator->validate()
#6 /opt/lampp/htdocs/so/protected/controllers/SiteController.php(94): LoginForm->validate()
#7 /opt/lampp/htdocs/so/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#8 /opt/lampp/htdocs/so/yii/framework/web/CController.php(308): CInlineAction->runWithParams()
#9 /opt/lampp/htdocs/so/yii/framework/web/CController.php(286): SiteController->runAction()
#10 /opt/lampp/htdocs/so/yii/framework/web/CController.php(265): SiteController->runActionWithFilters()
#11 /opt/lampp/htdocs/so/yii/framework/web/CWebApplication.php(282): SiteController->run()
#12 /opt/lampp/htdocs/so/yii/framework/web/CWebApplication.php(141): CWebApplication->runController()
#13 /opt/lampp/htdocs/so/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#14 /opt/lampp/htdocs/so/index.php(13): CWebApplication->run()
REQUEST_URI=/so/index.php?r=site/login
in /opt/lampp/htdocs/so/protected/components/UserIdentity.php (32)
in /opt/lampp/htdocs/so/protected/models/LoginForm.php (52)
in /opt/lampp/htdocs/so/protected/controllers/SiteController.php (94)
2013/12/26 09:32:21 [error] [php] Invalid argument supplied for foreach() (/opt/lampp/htdocs/so/yii/framework/web/auth/CPhpAuthManager.php:420)
Stack trace:
#0 /opt/lampp/htdocs/so/yii/framework/base/CModule.php(103): CWebApplication->getComponent()
#1 /opt/lampp/htdocs/so/protected/components/UserIdentity.php(32): CWebApplication->__get()
#2 /opt/lampp/htdocs/so/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#3 /opt/lampp/htdocs/so/yii/framework/validators/CInlineValidator.php(42): LoginForm->authenticate()
#4 /opt/lampp/htdocs/so/yii/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute()
#5 /opt/lampp/htdocs/so/yii/framework/base/CModel.php(159): CInlineValidator->validate()
#6 /opt/lampp/htdocs/so/protected/controllers/SiteController.php(94): LoginForm->validate()
#7 /opt/lampp/htdocs/so/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#8 /opt/lampp/htdocs/so/yii/framework/web/CController.php(308): CInlineAction->runWithParams()
#9 /opt/lampp/htdocs/so/yii/framework/web/CController.php(286): SiteController->runAction()
#10 /opt/lampp/htdocs/so/yii/framework/web/CController.php(265): SiteController->runActionWithFilters()
#11 /opt/lampp/htdocs/so/yii/framework/web/CWebApplication.php(282): SiteController->run()
#12 /opt/lampp/htdocs/so/yii/framework/web/CWebApplication.php(141): CWebApplication->runController()
#13 /opt/lampp/htdocs/so/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#14 /opt/lampp/htdocs/so/index.php(13): CWebApplication->run()
REQUEST_URI=/so/index.php?r=site/login
in /opt/lampp/htdocs/so/protected/components/UserIdentity.php (32)
in /opt/lampp/htdocs/so/protected/models/LoginForm.php (52)
in /opt/lampp/htdocs/so/protected/controllers/SiteController.php (94)
2013/12/26 09:32:35 [error] [php] Invalid argument supplied for foreach() (/opt/lampp/htdocs/so/yii/framework/web/auth/CPhpAuthManager.php:420)
Stack trace:
#0 /opt/lampp/htdocs/so/yii/framework/base/CModule.php(103): CWebApplication->getComponent()
#1 /opt/lampp/htdocs/so/protected/components/UserIdentity.php(32): CWebApplication->__get()
#2 /opt/lampp/htdocs/so/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#3 /opt/lampp/htdocs/so/yii/framework/validators/CInlineValidator.php(42): LoginForm->authenticate()
#4 /opt/lampp/htdocs/so/yii/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute()
#5 /opt/lampp/htdocs/so/yii/framework/base/CModel.php(159): CInlineValidator->validate()
#6 /opt/lampp/htdocs/so/protected/controllers/SiteController.php(94): LoginForm->validate()
#7 /opt/lampp/htdocs/so/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#8 /opt/lampp/htdocs/so/yii/framework/web/CController.php(308): CInlineAction->runWithParams()
#9 /opt/lampp/htdocs/so/yii/framework/web/CController.php(286): SiteController->runAction()
#10 /opt/lampp/htdocs/so/yii/framework/web/CController.php(265): SiteController->runActionWithFilters()
#11 /opt/lampp/htdocs/so/yii/framework/web/CWebApplication.php(282): SiteController->run()
#12 /opt/lampp/htdocs/so/yii/framework/web/CWebApplication.php(141): CWebApplication->runController()
#13 /opt/lampp/htdocs/so/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#14 /opt/lampp/htdocs/so/index.php(13): CWebApplication->run()
REQUEST_URI=/so/index.php?r=site/login
in /opt/lampp/htdocs/so/protected/components/UserIdentity.php (32)
in /opt/lampp/htdocs/so/protected/models/LoginForm.php (52)
in /opt/lampp/htdocs/so/protected/controllers/SiteController.php (94)
2013/12/26 09:36:43 [error] [php] Invalid argument supplied for foreach() (/opt/lampp/htdocs/so/yii/framework/web/auth/CPhpAuthManager.php:420)
Stack trace:
#0 /opt/lampp/htdocs/so/yii/framework/base/CModule.php(103): CWebApplication->getComponent()
#1 /opt/lampp/htdocs/so/protected/components/UserIdentity.php(32): CWebApplication->__get()
#2 /opt/lampp/htdocs/so/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#3 /opt/lampp/htdocs/so/yii/framework/validators/CInlineValidator.php(42): LoginForm->authenticate()
#4 /opt/lampp/htdocs/so/yii/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute()
#5 /opt/lampp/htdocs/so/yii/framework/base/CModel.php(159): CInlineValidator->validate()
#6 /opt/lampp/htdocs/so/protected/controllers/SiteController.php(94): LoginForm->validate()
#7 /opt/lampp/htdocs/so/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#8 /opt/lampp/htdocs/so/yii/framework/web/CController.php(308): CInlineAction->runWithParams()
#9 /opt/lampp/htdocs/so/yii/framework/web/CController.php(286): SiteController->runAction()
#10 /opt/lampp/htdocs/so/yii/framework/web/CController.php(265): SiteController->runActionWithFilters()
#11 /opt/lampp/htdocs/so/yii/framework/web/CWebApplication.php(282): SiteController->run()
#12 /opt/lampp/htdocs/so/yii/framework/web/CWebApplication.php(141): CWebApplication->runController()
#13 /opt/lampp/htdocs/so/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#14 /opt/lampp/htdocs/so/index.php(13): CWebApplication->run()
REQUEST_URI=/so/index.php?r=site/login
in /opt/lampp/htdocs/so/protected/components/UserIdentity.php (32)
in /opt/lampp/htdocs/so/protected/models/LoginForm.php (52)
in /opt/lampp/htdocs/so/protected/controllers/SiteController.php (94)
2013/12/26 09:40:19 [error] [php] Invalid argument supplied for foreach() (/opt/lampp/htdocs/so/yii/framework/web/auth/CPhpAuthManager.php:420)
Stack trace:
#0 /opt/lampp/htdocs/so/yii/framework/base/CModule.php(103): CWebApplication->getComponent()
#1 /opt/lampp/htdocs/so/protected/components/UserIdentity.php(32): CWebApplication->__get()
#2 /opt/lampp/htdocs/so/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#3 /opt/lampp/htdocs/so/yii/framework/validators/CInlineValidator.php(42): LoginForm->authenticate()
#4 /opt/lampp/htdocs/so/yii/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute()
#5 /opt/lampp/htdocs/so/yii/framework/base/CModel.php(159): CInlineValidator->validate()
#6 /opt/lampp/htdocs/so/protected/controllers/SiteController.php(94): LoginForm->validate()
#7 /opt/lampp/htdocs/so/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#8 /opt/lampp/htdocs/so/yii/framework/web/CController.php(308): CInlineAction->runWithParams()
#9 /opt/lampp/htdocs/so/yii/framework/web/CController.php(286): SiteController->runAction()
#10 /opt/lampp/htdocs/so/yii/framework/web/CController.php(265): SiteController->runActionWithFilters()
#11 /opt/lampp/htdocs/so/yii/framework/web/CWebApplication.php(282): SiteController->run()
#12 /opt/lampp/htdocs/so/yii/framework/web/CWebApplication.php(141): CWebApplication->runController()
#13 /opt/lampp/htdocs/so/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#14 /opt/lampp/htdocs/so/index.php(13): CWebApplication->run()
REQUEST_URI=/so/index.php?r=site/login
in /opt/lampp/htdocs/so/protected/components/UserIdentity.php (32)
in /opt/lampp/htdocs/so/protected/models/LoginForm.php (52)
in /opt/lampp/htdocs/so/protected/controllers/SiteController.php (94)
2013/12/26 09:45:04 [error] [exception.CException] exception 'CException' with message 'Property "User.role" is not defined.' in /opt/lampp/htdocs/so/yii/framework/base/CComponent.php:130
Stack trace:
#0 /opt/lampp/htdocs/so/yii/framework/db/ar/CActiveRecord.php(145): CComponent->__get('role')
#1 /opt/lampp/htdocs/so/protected/components/UserIdentity.php(33): CActiveRecord->__get('role')
#2 /opt/lampp/htdocs/so/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#3 /opt/lampp/htdocs/so/yii/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 /opt/lampp/htdocs/so/yii/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 /opt/lampp/htdocs/so/yii/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 /opt/lampp/htdocs/so/protected/controllers/SiteController.php(94): CModel->validate()
#7 /opt/lampp/htdocs/so/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#8 /opt/lampp/htdocs/so/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#9 /opt/lampp/htdocs/so/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#10 /opt/lampp/htdocs/so/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 /opt/lampp/htdocs/so/yii/framework/web/CWebApplication.php(282): CController->run('login')
#12 /opt/lampp/htdocs/so/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#13 /opt/lampp/htdocs/so/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#14 /opt/lampp/htdocs/so/index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/so/index.php?r=site/login
HTTP_REFERER=http://localhost/so/index.php?r=site/login
---
2013/12/26 09:56:06 [error] [exception.CException] exception 'CException' with message 'User and its behaviors do not have a method or closure named "validatePassword".' in /opt/lampp/htdocs/so/yii/framework/base/CComponent.php:266
Stack trace:
#0 /opt/lampp/htdocs/so/yii/framework/db/ar/CActiveRecord.php(227): CComponent->__call('validatePasswor...', Array)
#1 /opt/lampp/htdocs/so/protected/components/UserIdentity.php(26): CActiveRecord->__call('validatePasswor...', Array)
#2 /opt/lampp/htdocs/so/protected/components/UserIdentity.php(26): User->validatePassword('demo')
#3 /opt/lampp/htdocs/so/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#4 /opt/lampp/htdocs/so/yii/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#5 /opt/lampp/htdocs/so/yii/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#6 /opt/lampp/htdocs/so/yii/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#7 /opt/lampp/htdocs/so/protected/controllers/SiteController.php(94): CModel->validate()
#8 /opt/lampp/htdocs/so/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#9 /opt/lampp/htdocs/so/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /opt/lampp/htdocs/so/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /opt/lampp/htdocs/so/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /opt/lampp/htdocs/so/yii/framework/web/CWebApplication.php(282): CController->run('login')
#13 /opt/lampp/htdocs/so/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#14 /opt/lampp/htdocs/so/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /opt/lampp/htdocs/so/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/so/index.php?r=site/login
HTTP_REFERER=http://localhost/so/index.php?r=site/login
---
2013/12/26 09:56:43 [error] [exception.CException] exception 'CException' with message 'Unknown authorization item "".' in /opt/lampp/htdocs/so/yii/framework/web/auth/CPhpAuthManager.php:179
Stack trace:
#0 /opt/lampp/htdocs/so/protected/components/UserIdentity.php(35): CPhpAuthManager->assign(NULL, '1')
#1 /opt/lampp/htdocs/so/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#2 /opt/lampp/htdocs/so/yii/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#3 /opt/lampp/htdocs/so/yii/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 /opt/lampp/htdocs/so/yii/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#5 /opt/lampp/htdocs/so/protected/controllers/SiteController.php(94): CModel->validate()
#6 /opt/lampp/htdocs/so/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#7 /opt/lampp/htdocs/so/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#8 /opt/lampp/htdocs/so/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#9 /opt/lampp/htdocs/so/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 /opt/lampp/htdocs/so/yii/framework/web/CWebApplication.php(282): CController->run('login')
#11 /opt/lampp/htdocs/so/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#12 /opt/lampp/htdocs/so/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#13 /opt/lampp/htdocs/so/index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/so/index.php?r=site/login
HTTP_REFERER=http://localhost/so/index.php?r=site/login
---
2013/12/26 09:59:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "question/create".' in /opt/lampp/htdocs/so/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /opt/lampp/htdocs/so/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('question/create')
#1 /opt/lampp/htdocs/so/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /opt/lampp/htdocs/so/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/so/index.php?r=question/create
---
2013/12/26 09:59:26 [error] [exception.CException] exception 'CException' with message 'Unknown authorization item "".' in /opt/lampp/htdocs/so/yii/framework/web/auth/CPhpAuthManager.php:179
Stack trace:
#0 /opt/lampp/htdocs/so/protected/components/UserIdentity.php(35): CPhpAuthManager->assign(NULL, '2')
#1 /opt/lampp/htdocs/so/protected/models/LoginForm.php(52): UserIdentity->authenticate()
#2 /opt/lampp/htdocs/so/yii/framework/validators/CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#3 /opt/lampp/htdocs/so/yii/framework/validators/CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 /opt/lampp/htdocs/so/yii/framework/base/CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#5 /opt/lampp/htdocs/so/protected/controllers/SiteController.php(94): CModel->validate()
#6 /opt/lampp/htdocs/so/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionLogin()
#7 /opt/lampp/htdocs/so/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#8 /opt/lampp/htdocs/so/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#9 /opt/lampp/htdocs/so/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 /opt/lampp/htdocs/so/yii/framework/web/CWebApplication.php(282): CController->run('login')
#11 /opt/lampp/htdocs/so/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/login')
#12 /opt/lampp/htdocs/so/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#13 /opt/lampp/htdocs/so/index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/so/index.php?r=site/login
HTTP_REFERER=http://localhost/so/index.php?r=site/login
---
2013/12/26 10:19:44 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in /opt/lampp/htdocs/so/yii/framework/web/auth/CAccessControlFilter.php:182
Stack trace:
#0 /opt/lampp/htdocs/so/yii/framework/web/auth/CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 /opt/lampp/htdocs/so/yii/framework/web/filters/CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 /opt/lampp/htdocs/so/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 /opt/lampp/htdocs/so/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 /opt/lampp/htdocs/so/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 /opt/lampp/htdocs/so/yii/framework/web/CController.php(291): CFilterChain->run()
#6 /opt/lampp/htdocs/so/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /opt/lampp/htdocs/so/yii/framework/web/CWebApplication.php(282): CController->run('admin')
#8 /opt/lampp/htdocs/so/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('user/admin')
#9 /opt/lampp/htdocs/so/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /opt/lampp/htdocs/so/index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/so/index.php?r=user/admin
HTTP_REFERER=http://localhost/so/index.php?r=user
---
